import { useMemo, useState } from "react";
import { Panel } from "../../../core/ui/Panel";
import type { CataloguePackage } from "../../models/catalogue";
import { catalogueInstallState, installedCatalogueIdentity } from "../../models/catalogue";
import type { SelectedProtocolState } from "../../models/protocol-state";
import { catalogueErrorMessage } from "../../api/catalogue";

interface Props { packages: CataloguePackage[]; loading: boolean; error: string | null; protocolState: SelectedProtocolState | null; selectedAccounts: string[]; onRefresh: () => void; onInstall: (pkg: CataloguePackage, password?: string) => Promise<string>; }

export function CataloguePanel({ packages, loading, error, protocolState, selectedAccounts, onRefresh, onInstall }: Props) {
  const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [selected, setSelected] = useState<CataloguePackage | null>(null); const [password, setPassword] = useState(""); const [message, setMessage] = useState<string | null>(null); const [installing, setInstalling] = useState(false);
  const filtered = useMemo(() => packages.filter((pkg) => (type === "all" || pkg.packageType === type) && `${pkg.name} ${pkg.publisherDisplayName} ${pkg.datasetType ?? ""} ${pkg.datasetGroup ?? ""}`.toLowerCase().includes(query.toLowerCase())), [packages, query, type]);
  const install = () => { if (!selected) return; if (!window.confirm(`Queue ${selected.name} for ${selectedAccounts.length} selected account(s)?`)) return; setInstalling(true); setMessage(null); void onInstall(selected, selected.protected ? password : undefined).then((text) => setMessage(text)).catch((reason: unknown) => setMessage(catalogueErrorMessage(reason, "Catalogue package could not be queued."))).finally(() => { setPassword(""); setInstalling(false); }); };
  const installed = selected ? installedCatalogueIdentity(selected, protocolState?.accounts ?? []) : null;
  const failedResult = selected ? protocolState?.accounts.flatMap((account) => account.operationResults).find((result) => result.catalogueId === selected.catalogueId && result.status === "failed") : null;
  return <section className="dataset-section" aria-labelledby="catalogue-heading"><div className="section-heading"><h2 id="catalogue-heading">Esarus catalogue</h2><button className="secondary-button" type="button" onClick={onRefresh} disabled={loading}>{loading ? "Loading…" : "Refresh catalogue"}</button></div>{error ? <p className="discovery-error">{error}</p> : null}
    <Panel className="detail-panel"><div className="catalogue-filters"><label>Search <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Package or publisher" /></label><label>Type <select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All packages</option><option value="dataset">Datasets</option><option value="ruleset">Rulesets</option></select></label></div></Panel>
    {loading ? <Panel className="empty-panel"><p>Loading live catalogue…</p></Panel> : <div className="dataset-table-wrap"><table className="dataset-table"><thead><tr><th>Package</th><th>Publisher</th><th>Type</th><th>Dataset type/group</th><th>Revision</th><th>State</th><th>Action</th></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan={7}>No catalogue packages match.</td></tr> : filtered.map((pkg) => <CatalogueRow key={pkg.catalogueId} pkg={pkg} state={catalogueInstallState(pkg, protocolState?.accounts ?? [])} onSelect={() => { setSelected(pkg); setMessage(null); }} />)}</tbody></table></div>}
    {selected ? <Panel className="detail-panel"><h3>{selected.name}</h3><p className="status-detail">{selected.publisherDisplayName} · revision {selected.currentRevision}{selected.protected ? " · password protected" : ""}</p>{installed ? <p className="status-detail">Installed revision {installed.revision} · SHA-256 {installed.hash}</p> : null}{failedResult?.error ? <p className="discovery-error">RPE import failed: {failedResult.error.code} — {failedResult.error.detail}</p> : null}{selected.protected ? <label className="selector-row">Package password <input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label> : null}<p className="status-detail">Selected accounts: {selectedAccounts.length ? selectedAccounts.join(", ") : "none"}</p><button className="primary-button" type="button" disabled={installing || selected.packageType !== "dataset" || selectedAccounts.length === 0} onClick={install}>{installing ? "Queueing…" : catalogueInstallState(selected, protocolState?.accounts ?? []) === "update_available" ? "Queue update" : "Queue install"}</button>{selected.packageType !== "dataset" ? <p className="status-detail">Only dataset packages are installable through the current RPE protocol.</p> : null}{message ? <p className={message.startsWith("Queued") ? "status-detail" : "discovery-error"}>{message}</p> : null}</Panel> : null}</section>;
}

function CatalogueRow({ pkg, state, onSelect }: { pkg: CataloguePackage; state: string; onSelect: () => void }) { return <tr><td>{pkg.name}{pkg.protected ? " 🔒" : ""}</td><td>{pkg.publisherDisplayName}</td><td>{pkg.packageType}</td><td>{[pkg.datasetType, pkg.datasetGroup].filter(Boolean).join(" / ") || "—"}</td><td>{pkg.currentRevision}</td><td><span className={`dataset-status dataset-status-${state}`}>{state.replaceAll("_", " ")}</span></td><td><button className="link-button" type="button" onClick={onSelect}>View</button></td></tr>; }
