import { describe, expect, it } from "vitest";
import type { ManagerUpdateHandle, ManagerUpdaterApi } from "../api/manager-updates";
import type { ManagerUpdateState } from "../models/manager-updates";
import { ManagerUpdateService } from "./manager-updates";

function update(overrides: Partial<ManagerUpdateHandle> = {}): ManagerUpdateHandle { return { currentVersion: "0.1.0", version: "0.1.1", date: "2026-09-22", body: "Notes", close: async () => undefined, downloadAndInstall: async (onEvent) => { onEvent?.({ event: "Started", data: { contentLength: 10 } }); onEvent?.({ event: "Progress", data: { chunkLength: 4 } }); onEvent?.({ event: "Progress", data: { chunkLength: 6 } }); onEvent?.({ event: "Finished" }); }, ...overrides }; }
function service(check: ManagerUpdaterApi["check"]) { const states: ManagerUpdateState[] = []; return { states, instance: new ManagerUpdateService({ getCurrentVersion: async () => "0.1.0", check }, (state) => states.push(state)) }; }

describe("ManagerUpdateService", () => {
  it("reports up to date when Tauri finds no update", async () => { const subject = service(async () => null); await subject.instance.checkForManagerUpdate(); expect(subject.states.at(-1)).toMatchObject({ status: "up_to_date", installedVersion: "0.1.0", update: null }); });
  it("retains Tauri update metadata for explicit installation", async () => { const subject = service(async () => update()); await subject.instance.checkForManagerUpdate(); expect(subject.states.at(-1)).toMatchObject({ status: "update_available", installedVersion: "0.1.0", update: { currentVersion: "0.1.0", availableVersion: "0.1.1", releaseNotes: "Notes" } }); });
  it("keeps explicit check failures visible", async () => { const subject = service(async () => { throw new Error("manifest signature rejected"); }); await subject.instance.checkForManagerUpdate(); expect(subject.states.at(-1)).toMatchObject({ status: "failed", error: "manifest signature rejected" }); });
  it("publishes deterministic download progress and releases the update at installer handoff", async () => { let closed = false; const subject = service(async () => update({ close: async () => { closed = true; } })); await subject.instance.checkForManagerUpdate(); await subject.instance.installManagerUpdate(); expect(subject.states).toContainEqual(expect.objectContaining({ status: "downloading", downloadedBytes: 4, totalBytes: 10 })); expect(subject.states.at(-1)).toMatchObject({ status: "installing" }); expect(closed).toBe(true); });
  it("returns to an operable failed state when installation fails before handoff", async () => { const subject = service(async () => update({ downloadAndInstall: async () => { throw new Error("download failed"); } })); await subject.instance.checkForManagerUpdate(); await subject.instance.installManagerUpdate(); expect(subject.states.at(-1)).toMatchObject({ status: "failed", error: "download failed" }); });
  it("replaces stale update and error state on a later check", async () => { let closed = false; let next: ManagerUpdateHandle | null = update({ close: async () => { closed = true; } }); const subject = service(async () => next); await subject.instance.checkForManagerUpdate(); next = null; await subject.instance.checkForManagerUpdate(); expect(subject.states.at(-1)).toMatchObject({ status: "up_to_date", update: null, error: null }); expect(closed).toBe(true); });
});
